config/routes.rb
Rails.application.routes.draw do
  resources :komponentenservices
  resources :komponententyps
  resources :aufgabens
  get 'aufgabens/new/:applikation_id', to: 'aufgabens#new'
  
  resources :users
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  resources :hardwaretypzuservers
  get 'hardwaretypzuservers/new/:server_id', to: 'hardwaretypzuservers#new'
  get 'hardwaretypzuservers/:id/edit', to: 'hardwaretypzuservers#edit'
  get 'hardwaretypzuservers/:id/edit/:server_id', to: 'hardwaretypzuservers#edit'
  resources :hardwaretyps
  resources :stuves
  get 'stuves/new/:kunde_id', to: 'stuves#new'
  get 'stuves/index/:kunde_id', to: 'stuves#index'
  resources :techbenutzers
  get 'techbenutzers/new/:applikation_id', to: 'techbenutzers#new'
  resources :supportmatrices
  resources :monitoringzusks
  #get 'monitoringzusks/new/:komponente_id/:server_id', to 'monitoringzusks#new'
  get 'monitoringzusks/new/k/:komponente_id', to: 'monitoringzusks#new'
  get 'monitoringzusks/new/s/:server_id', to: 'monitoringzusks#new'
  get 'supportmatrices/new/:applikation_id', to: 'supportmatrices#new'
  get 'supportmatrices/new/:applikation_id/:was', to: 'supportmatrices#new'
  get 'supportmatrices/edit/:id/edit/:was', to: 'supportmatrices#edit'
  resources :monitorings
  resources :referenzs
  get 'referenzs/new/:applikation_id', to: 'referenzs#new'
  get 'referenzs/:id/edit/:applikation_id', to: 'referenzs#edit'
  resources :komponentes
  get 'komponentes/new/:applikation_id', to: 'komponentes#new'
  get 'komponentes/:id/edit/:applikation_id', to: 'komponentes#edit'
  get 'start/index', to: 'start#index'
  get 'start/index/:id', to: 'start#index'
  get 'start/index/:id/:applikation_id', to: 'start#index'
  resources :applikations
  get 'applikations/index/:kunde_id', to: 'applikations#index'
  get 'applikations/new/:kunde_id', to: 'applikations#new'
  resources :fachgruppes
  resources :dienstleisters
  get 'dienstleisters/index/:kunde_id', to: 'dienstleisters#index'
  get 'dienstleisters/new/:kunde_id', to: 'dienstleisters#new'
  resources :servers
  get 'servers/index/:kunde_id', to: 'servers#index'
  get 'servers/new/:kunde_id', to: 'servers#new'
  resources :betriebssystems
  resources :betriebssystemtyps
  resources :kundes


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  
  root to:'start#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applikation.rb
class Applikation < ApplicationRecord
  belongs_to :kunde
  has_many :komponente
  has_many :referenz
  has_many :techbenutzer
end

app/models/aufgaben.rb
class Aufgaben < ApplicationRecord
  belongs_to :applikation
end

app/models/benutzer.rb
class Benutzer < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/betriebssystem.rb
class Betriebssystem < ApplicationRecord
  belongs_to :betriebssystemtyp
end

app/models/dienstleister.rb
class Dienstleister < ApplicationRecord
end

app/models/fachgruppe.rb
class Fachgruppe < ApplicationRecord
end

app/models/hardwaretyp.rb
class Hardwaretyp < ApplicationRecord
end

app/models/komponente.rb
class Komponente < ApplicationRecord
  belongs_to :applikation
  belongs_to :server


  def komponente_mit_host
    applikationsname = Applikation.find(applikation_id).name
    hostname = Server.find(server_id).name
    stufenname = Stufe.find(stufe_id).name
    "#{applikationsname} - #{stufenname} - #{hostname} - #{name}"
  end
end

app/models/komponententyp.rb
class Komponententyp < ApplicationRecord
end

app/models/kunde.rb
class Kunde < ApplicationRecord
    has_many :applikation
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
    def name_mit_werte
        "#{name}(#{werte})"
      end
end

app/models/monitoringzusk.rb
class Monitoringzusk < ApplicationRecord
  belongs_to :monitoring
end

app/models/referenz.rb
class Referenz < ApplicationRecord
  belongs_to :applikation
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :kunde
  belongs_to :betriebssystem
  has_many  :komponente
end

app/models/stufe.rb
class Stufe < ApplicationRecord
  belongs_to :kunde
end

app/models/supportmatrix.rb
class Supportmatrix < ApplicationRecord
  belongs_to :applikation
end

app/models/techbenutzer.rb
class Techbenutzer < ApplicationRecord
  belongs_to :applikation
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/applikations_controller.rb
class ApplikationsController < ApplicationController
  before_action :set_applikation, only: [:show, :edit, :update, :destroy]

  # GET /applikations
  # GET /applikations.json
  def index
    @applikations = Applikation.all
    @kundes = Kunde.all
  end

  # GET /applikations/1
  # GET /applikations/1.json
  def show
    @kundes = Kunde.all
  end

  # GET /applikations/new
  def new
    @applikation = Applikation.new
    @kundes = Kunde.all
  end

  # GET /applikations/1/edit
  def edit
    @kundes = Kunde.all
  end

  # POST /applikations
  # POST /applikations.json
  def create
    @kundes = Kunde.all
    @applikation = Applikation.new(applikation_params)

    respond_to do |format|
      if @applikation.save
        format.html { redirect_to "/start/index/#{applikation_params[:kunde_id]}/#{@applikation.id}" , notice: 'Applikation was successfully created.' }
        format.json { render :show, status: :created, location: @applikation }
      else
        format.html { render :new }
        format.json { render json: @applikation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applikations/1
  # PATCH/PUT /applikations/1.json
  def update
    @kundes = Kunde.all
    respond_to do |format|
      if @applikation.update(applikation_params)
        format.html { redirect_to "/start/index/#{applikation_params[:kunde_id]}/#{@applikation.id}", notice: 'Applikation was successfully updated.' }
        format.json { render :show, status: :ok, location: @applikation }
      else
        format.html { render :edit }
        format.json { render json: @applikation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applikations/1
  # DELETE /applikations/1.json
  def destroy
    @kundes = Kunde.all
    @applikation.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'Applikation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applikation
      @applikation = Applikation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def applikation_params
      params.require(:applikation).permit(:name, :beschreibung, :kunde_id)
    end
end

app/helpers/applikations_helper.rb
module ApplikationsHelper
end

app/helpers/kundes_helper.rb
module KundesHelper
end

app/helpers/stuves_helper.rb
module StuvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applikations/_form.html.erb
<%= form_with(model: applikation, local: true) do |form| %>
  <% if applikation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applikation.errors.count, "error") %> prohibited this applikation from being saved:</h2>

      <ul>
        <% applikation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :beschreibung %>
    <%= form.text_area :beschreibung %>
  </div>

  <div class="field">
    <%= form.label :kunde_id %>
    <% if params[:kunde_id].nil? %>
      <%= form.collection_select(:kunde_id,Kunde.all,:id,:name, :selected => @applikation.kunde_id)%> 
    <% else %>
       <%= form.collection_select(:kunde_id,Kunde.all,:id,:name, :selected => params[:kunde_id] )%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applikations/edit.html.erb
<h1>Editing Applikation</h1>

<%= render 'form', applikation: @applikation %>

<%= link_to 'Anzeigen', @applikation %> |
<%= link_to 'Zurück', request.referer %>

app/views/applikations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applikations</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beschreibung</th>
      <th>Kunde</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%
      
        @applikations.where(kunde_id: params[:kunde_id]).each do |applikation| 
     
     
    %>
      <tr>
        <td><%= applikation.name %></td>
        <td><%= applikation.beschreibung %></td>
        <td><%= Kunde.find(applikation.kunde_id).name %></td>
        <td><%= link_to 'Anzeigen', applikation %></td>
        <td><%= link_to 'Bearbeiten', edit_applikation_path(applikation) %></td>
        <td>
          <%  # wenn es angehängte Komponenten gibt kann die Applikation niht gelöscht werden 
            if  applikation.komponente.count  == 0 %>
           <%= link_to 'Löschen', applikation, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
          <% else %>
            Es gibt noch Komponenten
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Applikation', new_applikation_path %>

app/views/applikations/new.html.erb
<h1>New Applikation</h1>

<%= render 'form', applikation: @applikation %>

<%= link_to 'Zurück', request.referer %>

app/views/applikations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applikation.name %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @applikation.beschreibung %>
</p>

<p>
  <strong>Kunde:</strong>
  <%= Kunde.find(@applikation.kunde_id).name %>
</p>

<%= link_to 'Bearbeiten', edit_applikation_path(@applikation) %> |
<%= link_to 'Zurück', applikations_path %>