config/routes.rb
Rails.application.routes.draw do
  resources :komponentenservices
  resources :komponententyps
  resources :aufgabens
  get 'aufgabens/new/:applikation_id', to: 'aufgabens#new'
  
  resources :users
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  resources :hardwaretypzuservers
  get 'hardwaretypzuservers/new/:server_id', to: 'hardwaretypzuservers#new'
  get 'hardwaretypzuservers/:id/edit', to: 'hardwaretypzuservers#edit'
  get 'hardwaretypzuservers/:id/edit/:server_id', to: 'hardwaretypzuservers#edit'
  resources :hardwaretyps
  resources :stuves
  get 'stuves/new/:kunde_id', to: 'stuves#new'
  get 'stuves/index/:kunde_id', to: 'stuves#index'
  resources :techbenutzers
  get 'techbenutzers/new/:applikation_id', to: 'techbenutzers#new'
  resources :supportmatrices
  resources :monitoringzusks
  #get 'monitoringzusks/new/:komponente_id/:server_id', to 'monitoringzusks#new'
  get 'monitoringzusks/new/k/:komponente_id', to: 'monitoringzusks#new'
  get 'monitoringzusks/new/s/:server_id', to: 'monitoringzusks#new'
  get 'supportmatrices/new/:applikation_id', to: 'supportmatrices#new'
  get 'supportmatrices/new/:applikation_id/:was', to: 'supportmatrices#new'
  get 'supportmatrices/edit/:id/edit/:was', to: 'supportmatrices#edit'
  resources :monitorings
  resources :referenzs
  get 'referenzs/new/:applikation_id', to: 'referenzs#new'
  get 'referenzs/:id/edit/:applikation_id', to: 'referenzs#edit'
  resources :komponentes
  get 'komponentes/new/:applikation_id', to: 'komponentes#new'
  get 'komponentes/:id/edit/:applikation_id', to: 'komponentes#edit'
  get 'start/index', to: 'start#index'
  get 'start/index/:id', to: 'start#index'
  get 'start/index/:id/:applikation_id', to: 'start#index'
  resources :applikations
  get 'applikations/index/:kunde_id', to: 'applikations#index'
  get 'applikations/new/:kunde_id', to: 'applikations#new'
  resources :fachgruppes
  resources :dienstleisters
  get 'dienstleisters/index/:kunde_id', to: 'dienstleisters#index'
  get 'dienstleisters/new/:kunde_id', to: 'dienstleisters#new'
  resources :servers
  get 'servers/index/:kunde_id', to: 'servers#index'
  get 'servers/new/:kunde_id', to: 'servers#new'
  resources :betriebssystems
  resources :betriebssystemtyps
  resources :kundes


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  
  root to:'start#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applikation.rb
class Applikation < ApplicationRecord
  belongs_to :kunde
  has_many :komponente
  has_many :referenz
  has_many :techbenutzer
end

app/models/aufgaben.rb
class Aufgaben < ApplicationRecord
  belongs_to :applikation
end

app/models/benutzer.rb
class Benutzer < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/betriebssystem.rb
class Betriebssystem < ApplicationRecord
  belongs_to :betriebssystemtyp
end

app/models/dienstleister.rb
class Dienstleister < ApplicationRecord
end

app/models/fachgruppe.rb
class Fachgruppe < ApplicationRecord
end

app/models/hardwaretyp.rb
class Hardwaretyp < ApplicationRecord
end

app/models/komponente.rb
class Komponente < ApplicationRecord
  belongs_to :applikation
  belongs_to :server


  def komponente_mit_host
    applikationsname = Applikation.find(applikation_id).name
    hostname = Server.find(server_id).name
    stufenname = Stufe.find(stufe_id).name
    "#{applikationsname} - #{stufenname} - #{hostname} - #{name}"
  end
end

app/models/komponententyp.rb
class Komponententyp < ApplicationRecord
end

app/models/kunde.rb
class Kunde < ApplicationRecord
    has_many :applikation
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
    def name_mit_werte
        "#{name}(#{werte})"
      end
end

app/models/monitoringzusk.rb
class Monitoringzusk < ApplicationRecord
  belongs_to :monitoring
end

app/models/referenz.rb
class Referenz < ApplicationRecord
  belongs_to :applikation
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :kunde
  belongs_to :betriebssystem
  has_many  :komponente
end

app/models/stufe.rb
class Stufe < ApplicationRecord
  belongs_to :kunde
end

app/models/supportmatrix.rb
class Supportmatrix < ApplicationRecord
  belongs_to :applikation
end

app/models/techbenutzer.rb
class Techbenutzer < ApplicationRecord
  belongs_to :applikation
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/aufgabens_controller.rb
class AufgabensController < ApplicationController
  before_action :set_aufgaben, only: [:show, :edit, :update, :destroy]

  # GET /aufgabens
  # GET /aufgabens.json
  def index
    @kundes = Kunde.all
    @aufgabens = Aufgaben.all
  end

  # GET /aufgabens/1
  # GET /aufgabens/1.json
  def show
    @kundes = Kunde.all
  end

  # GET /aufgabens/new
  def new
    @kundes = Kunde.all
    @aufgaben = Aufgaben.new
  end

  # GET /aufgabens/1/edit
  def edit
    @kundes = Kunde.all
  end

  # POST /aufgabens
  # POST /aufgabens.json
  def create
    @kundes = Kunde.all
    @aufgaben = Aufgaben.new(aufgaben_params)

    respond_to do |format|
      if @aufgaben.save
        format.html { redirect_to "/start/index/#{Applikation.find(@aufgaben.applikation_id).kunde_id}/#{@aufgaben.applikation_id}", notice: 'Aufgabe wurde hinzufügt.' }
        format.json { render :show, status: :created, location: @aufgaben }
      else
        format.html { render :new }
        format.json { render json: @aufgaben.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aufgabens/1
  # PATCH/PUT /aufgabens/1.json
  def update
    @kundes = Kunde.all
    respond_to do |format|
      if @aufgaben.update(aufgaben_params)
        format.html { redirect_to "/start/index/#{Applikation.find(@aufgaben.applikation_id).kunde_id}/#{@aufgaben.applikation_id}" ,notice: 'Die Aufgabe wurde aktualisiert.' }
        format.html { redirect_to @aufgaben, notice: 'Die Aufgabe wurde aktualisiert.' }
        format.json { render :show, status: :ok, location: @aufgaben }
      else
        format.html { render :edit }
        format.json { render json: @aufgaben.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aufgabens/1
  # DELETE /aufgabens/1.json
  def destroy
    @kundes = Kunde.all
    @aufgaben.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Die Aufgabe wurde gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aufgaben
      @aufgaben = Aufgaben.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aufgaben_params
      params.require(:aufgaben).permit(:name, :zeitpunkt, :beschreibung, :applikation_id)
    end
end

app/helpers/aufgabens_helper.rb
module AufgabensHelper
end

app/helpers/kundes_helper.rb
module KundesHelper
end

app/helpers/stuves_helper.rb
module StuvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aufgabens/_form.html.erb
<%= form_with(model: aufgaben, local: true) do |form| %>
  <% if aufgaben.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aufgaben.errors.count, "error") %> prohibited this aufgaben from being saved:</h2>

      <ul>
        <% aufgaben.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :zeitpunkt %>
    <%= form.text_field :zeitpunkt %>
  </div>

  <div class="field">
    <%= form.label :beschreibung %>
    <%= form.text_area :beschreibung %>
  </div>

  <div class="field">
    <%= form.label :applikation_id %> 
    <%= form.collection_select(:applikation_id,Applikation.all,:id,:name, :selected => params[:applikation_id])%> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aufgabens/edit.html.erb
<h1>Editing Aufgaben</h1>

<%= render 'form', aufgaben: @aufgaben %>

<%= link_to 'Show', @aufgaben %> |
<%= link_to 'Zurück', request.referer %>

app/views/aufgabens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aufgabens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Zeitpunkt</th>
      <th>Beschreibung</th>
      <th>Applikation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aufgabens.each do |aufgaben| %>
      <tr>
        <td><%= aufgaben.name %></td>
        <td><%= aufgaben.zeitpunkt %></td>
        <td><%= aufgaben.beschreibung %></td>
        <td><%= aufgaben.applikation_id %></td>
        <td><%= link_to 'Anzeigen', aufgaben %></td>
        <td><%= link_to 'Bearbeiten', edit_aufgaben_path(aufgaben) %></td>
        <td><%= link_to 'Löschen', aufgaben, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Aufgaben', new_aufgaben_path %>

app/views/aufgabens/new.html.erb
<h1>Neue Aufgaben</h1>

<%= render 'form', aufgaben: @aufgaben %>

<%= link_to 'Zurück', request.referer %>

app/views/aufgabens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @aufgaben.name %>
</p>

<p>
  <strong>Zeitpunkt:</strong>
  <%= @aufgaben.zeitpunkt %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @aufgaben.beschreibung %>
</p>

<p>
  <strong>Applikation:</strong>
  <%= @aufgaben.applikation_id %>
</p>

<%= link_to 'Edit', edit_aufgaben_path(@aufgaben) %> |
<%= link_to 'Back', aufgabens_path %>