config/routes.rb
Rails.application.routes.draw do
  resources :komponentenservices
  resources :komponententyps
  resources :aufgabens
  get 'aufgabens/new/:applikation_id', to: 'aufgabens#new'
  
  resources :users
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  resources :hardwaretypzuservers
  get 'hardwaretypzuservers/new/:server_id', to: 'hardwaretypzuservers#new'
  get 'hardwaretypzuservers/:id/edit', to: 'hardwaretypzuservers#edit'
  get 'hardwaretypzuservers/:id/edit/:server_id', to: 'hardwaretypzuservers#edit'
  resources :hardwaretyps
  resources :stuves
  get 'stuves/new/:kunde_id', to: 'stuves#new'
  get 'stuves/index/:kunde_id', to: 'stuves#index'
  resources :techbenutzers
  get 'techbenutzers/new/:applikation_id', to: 'techbenutzers#new'
  resources :supportmatrices
  resources :monitoringzusks
  #get 'monitoringzusks/new/:komponente_id/:server_id', to 'monitoringzusks#new'
  get 'monitoringzusks/new/k/:komponente_id', to: 'monitoringzusks#new'
  get 'monitoringzusks/new/s/:server_id', to: 'monitoringzusks#new'
  get 'supportmatrices/new/:applikation_id', to: 'supportmatrices#new'
  get 'supportmatrices/new/:applikation_id/:was', to: 'supportmatrices#new'
  get 'supportmatrices/edit/:id/edit/:was', to: 'supportmatrices#edit'
  resources :monitorings
  resources :referenzs
  get 'referenzs/new/:applikation_id', to: 'referenzs#new'
  get 'referenzs/:id/edit/:applikation_id', to: 'referenzs#edit'
  resources :komponentes
  get 'komponentes/new/:applikation_id', to: 'komponentes#new'
  get 'komponentes/:id/edit/:applikation_id', to: 'komponentes#edit'
  get 'start/index', to: 'start#index'
  get 'start/index/:id', to: 'start#index'
  get 'start/index/:id/:applikation_id', to: 'start#index'
  resources :applikations
  get 'applikations/index/:kunde_id', to: 'applikations#index'
  get 'applikations/new/:kunde_id', to: 'applikations#new'
  resources :fachgruppes
  resources :dienstleisters
  get 'dienstleisters/index/:kunde_id', to: 'dienstleisters#index'
  get 'dienstleisters/new/:kunde_id', to: 'dienstleisters#new'
  resources :servers
  get 'servers/index/:kunde_id', to: 'servers#index'
  get 'servers/new/:kunde_id', to: 'servers#new'
  resources :betriebssystems
  resources :betriebssystemtyps
  resources :kundes


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  
  root to:'start#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applikation.rb
class Applikation < ApplicationRecord
  belongs_to :kunde
  has_many :komponente
  has_many :referenz
  has_many :techbenutzer
end

app/models/aufgaben.rb
class Aufgaben < ApplicationRecord
  belongs_to :applikation
end

app/models/benutzer.rb
class Benutzer < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
end

app/models/betriebssystem.rb
class Betriebssystem < ApplicationRecord
  belongs_to :betriebssystemtyp
end

app/models/dienstleister.rb
class Dienstleister < ApplicationRecord
end

app/models/fachgruppe.rb
class Fachgruppe < ApplicationRecord
end

app/models/hardwaretyp.rb
class Hardwaretyp < ApplicationRecord
end

app/models/komponente.rb
class Komponente < ApplicationRecord
  belongs_to :applikation
  belongs_to :server


  def komponente_mit_host
    applikationsname = Applikation.find(applikation_id).name
    hostname = Server.find(server_id).name
    stufenname = Stufe.find(stufe_id).name
    "#{applikationsname} - #{stufenname} - #{hostname} - #{name}"
  end
end

app/models/komponententyp.rb
class Komponententyp < ApplicationRecord
end

app/models/kunde.rb
class Kunde < ApplicationRecord
    has_many :applikation
end

app/models/monitoring.rb
class Monitoring < ApplicationRecord
    def name_mit_werte
        "#{name}(#{werte})"
      end
end

app/models/monitoringzusk.rb
class Monitoringzusk < ApplicationRecord
  belongs_to :monitoring
end

app/models/referenz.rb
class Referenz < ApplicationRecord
  belongs_to :applikation
end

app/models/server.rb
class Server < ApplicationRecord
  belongs_to :kunde
  belongs_to :betriebssystem
  has_many  :komponente
end

app/models/stufe.rb
class Stufe < ApplicationRecord
  belongs_to :kunde
end

app/models/supportmatrix.rb
class Supportmatrix < ApplicationRecord
  belongs_to :applikation
end

app/models/techbenutzer.rb
class Techbenutzer < ApplicationRecord
  belongs_to :applikation
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/hardwaretyps_controller.rb
class HardwaretypsController < ApplicationController
  before_action :set_hardwaretyp, only: [:show, :edit, :update, :destroy]

  # GET /hardwaretyps
  # GET /hardwaretyps.json
  def index
    @kundes = Kunde.all
    @hardwaretyps = Hardwaretyp.all
  end

  # GET /hardwaretyps/1
  # GET /hardwaretyps/1.json
  def show
    @kundes = Kunde.all
  end

  # GET /hardwaretyps/new
  def new
    @kundes = Kunde.all
    @hardwaretyp = Hardwaretyp.new
  end

  # GET /hardwaretyps/1/edit
  def edit
    @kundes = Kunde.all
  end

  # POST /hardwaretyps
  # POST /hardwaretyps.json
  def create
    @kundes = Kunde.all
    @hardwaretyp = Hardwaretyp.new(hardwaretyp_params)

    respond_to do |format|
      if @hardwaretyp.save
        format.html { redirect_to @hardwaretyp, notice: 'Hardwaretyp was successfully created.' }
        format.json { render :show, status: :created, location: @hardwaretyp }
      else
        format.html { render :new }
        format.json { render json: @hardwaretyp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hardwaretyps/1
  # PATCH/PUT /hardwaretyps/1.json
  def update
    @kundes = Kunde.all
    respond_to do |format|
      if @hardwaretyp.update(hardwaretyp_params)
        format.html { redirect_to @hardwaretyp, notice: 'Hardwaretyp was successfully updated.' }
        format.json { render :show, status: :ok, location: @hardwaretyp }
      else
        format.html { render :edit }
        format.json { render json: @hardwaretyp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hardwaretyps/1
  # DELETE /hardwaretyps/1.json
  def destroy
    @kundes = Kunde.all
    @hardwaretyp.destroy
    respond_to do |format|
      format.html { redirect_to hardwaretyps_url, notice: 'Hardwaretyp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hardwaretyp
      @hardwaretyp = Hardwaretyp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hardwaretyp_params
      params.require(:hardwaretyp).permit(:name)
    end
end

app/helpers/hardwaretyps_helper.rb
module HardwaretypsHelper
end

app/helpers/kundes_helper.rb
module KundesHelper
end

app/helpers/stuves_helper.rb
module StuvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hardwaretyps/_form.html.erb
<%= form_with(model: hardwaretyp, local: true) do |form| %>
  <% if hardwaretyp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hardwaretyp.errors.count, "error") %> prohibited this hardwaretyp from being saved:</h2>

      <ul>
        <% hardwaretyp.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hardwaretyps/edit.html.erb
<h1>Editing Hardwaretyp</h1>

<%= render 'form', hardwaretyp: @hardwaretyp %>

<%= link_to 'Anzeigen', @hardwaretyp %> |
<%= link_to 'Zurück', hardwaretyps_path %>

app/views/hardwaretyps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hardwaretyps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hardwaretyps.each do |hardwaretyp| %>
      <tr>
        <td><%= hardwaretyp.name %></td>
        <td><%= link_to 'Anzeigen', hardwaretyp %></td>
        <td><%= link_to 'Bearbeiten', edit_hardwaretyp_path(hardwaretyp) %></td>
        <td><%= link_to 'Löschen', hardwaretyp, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuer Hardwaretyp', new_hardwaretyp_path %>

app/views/hardwaretyps/new.html.erb
<h1>New Hardwaretyp</h1>

<%= render 'form', hardwaretyp: @hardwaretyp %>

<%= link_to 'Zurück', hardwaretyps_path %>

app/views/hardwaretyps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hardwaretyp.name %>
</p>

<%= link_to 'Bearbeiten', edit_hardwaretyp_path(@hardwaretyp) %> |
<%= link_to 'Zurück', hardwaretyps_path %>